/* Setting up PROD DB */
create database prod;
use prod;
create table firestation(
STATION_NUMBER int PRIMARY KEY AUTO_INCREMENT,
ADDRESS VARCHAR(250) NOT NULL);

create table person(
NAME VARCHAR(250) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(250) NOT NULL,
LAST_NAME VARCHAR(250) NOT NULL,
ADDRESS VARCHAR(250) NOT NULL,
CITY VARCHAR(250) NOT NULL,
ZIP int NOT NULL,
PHONE VARCHAR(250) NOT NULL,
EMAIL VARCHAR(250) NOT NULL,
FOREIGN KEY (STATION_NUMBER)
REFERENCES firestation(STATION_NUMBER));

 create table medicalreport(
 NAME VARCHAR(250) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(250) NOT NULL,
LAST_NAME VARCHAR(250) NOT NULL,
BIRTHDATE DATE  NOT NULL,
MEDICATIONS VARCHAR NOT NULL,
 FOREIGN KEY (NAME)
 REFERENCES person(NAME));
 
commit;

/* Setting up TEST DB */
create database test;
use test;

create table firestation(
STATION_NUMBER int PRIMARY KEY AUTO_INCREMENT,
ADDRESS VARCHAR(250) NOT NULL);

create table person(
NAME VARCHAR(250) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(250) NOT NULL,
LAST_NAME VARCHAR(250) NOT NULL,
ADDRESS VARCHAR(250) NOT NULL,
CITY VARCHAR(250) NOT NULL,
ZIP int NOT NULL,
PHONE VARCHAR(250) NOT NULL,
EMAIL VARCHAR(250) NOT NULL,
FOREIGN KEY (STATION_NUMBER)
REFERENCES firestation(STATION_NUMBER));

create table medicalreport(
NAME VARCHAR(250) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(250) NOT NULL,
LAST_NAME VARCHAR(250) NOT NULL,
BIRTHDATE DATE  NOT NULL,
MEDICATIONS VARCHAR NOT NULL,
FOREIGN KEY (NAME)
REFERENCES person(NAME));
 
commit;