package com.safetynet.api.service.alertssafetynetservice;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import com.safetynet.api.model.FireStation;
import com.safetynet.api.model.Person;
import com.safetynet.api.service.dataservice.FireStationService;
import com.safetynet.api.service.dataservice.PersonService;
@SpringBootTest
class SearchingInfoPhoneOfResidentsByStationNumberImplTest {
	@Autowired
	private SearchingInfoPhoneOfResidentsByStationNumberImpl infoPhoneOfResidentsByStationNumberUnderTest;

	@MockBean
	private FireStationService fireStationService;

	@MockBean
	private PersonService personService;
	
	private static Person personTest1;
	private static Person personTest2;
	private static List<Person> listOfPersonsTest;
	private static FireStation firestationTest1;
	private static FireStation firestationTest2;
	private static FireStation firestationTest3;
	private static List<FireStation> listOfFireStationsTest1;
	private static List<FireStation> listOfFireStationsTest2;
	
	@BeforeAll
	static void setUp() {
		personTest1 = new Person("Millie", "Leperlier", "45 quartier du port de Vannes","Vannes", "56000","841-874-2512",
				"millie@email.com");
		personTest1.setId("Millie Leperlier");
		personTest2 = new Person("Minnie", "Cooper", "12 rue des combattants", "Vannes", "40100", "841-874-7784",
				"millie@email.com");
		personTest2.setId("John Leperlier");
		listOfPersonsTest = new ArrayList<Person>();
		listOfPersonsTest.add(personTest1);
		listOfPersonsTest.add(personTest2);
		
		firestationTest1= new FireStation("5", "45 quartier du port de Vannes");
		firestationTest1.setId("45-5-65");
		firestationTest2= new FireStation("5", "112 address");
		firestationTest2.setId("112-5-41");
		firestationTest3= new FireStation("7", "78 boulevard du soldat inconnu");
		firestationTest3.setId("78-7-23");
		listOfFireStationsTest1 = new ArrayList<FireStation>();
		listOfFireStationsTest1.add(firestationTest1);
		listOfFireStationsTest1.add(firestationTest2);
		listOfFireStationsTest2 = new ArrayList<FireStation>();
		listOfFireStationsTest2.add(firestationTest3);
	}
	
	@Test
	void testSearchInfoOfResident() throws Exception {
		when(personService.getAllPersons()).thenReturn(listOfPersonsTest);
		when(fireStationService.getFireStationsByStationNumber( "5")).thenReturn(listOfFireStationsTest1);
		
		try {
			List<Map<String, String>> resultListOfPhonesOfResidentsOfStationNumber= infoPhoneOfResidentsByStationNumberUnderTest
					.searchInfoOfResident("5");
			
			verify(personService).getAllPersons();
			verify(fireStationService).getFireStationsByStationNumber(any(String.class));
			assertFalse(resultListOfPhonesOfResidentsOfStationNumber.isEmpty());
			//assertion all phones of residents in of map generated by the method searchInfoOfResident with station number '5'
			assertThat(resultListOfPhonesOfResidentsOfStationNumber).filteredOn("phone",personTest1.getPhone()).isNotNull();
			assertThat(resultListOfPhonesOfResidentsOfStationNumber).filteredOn("phone",personTest2.getPhone()).isNotNull();
		} catch (AssertionError e) {
			fail(e.getMessage());
		}
	}

	@Test
	@DisplayName("Given no existing stationNumber 6  when generate a map with info of resident  the method should error and null ")
	void testSearchInfoOfResident_WithStationNumberNotFound() throws Exception {
		when(fireStationService.getFireStationsByStationNumber( "6")).thenThrow(NullPointerException.class);
		
		try {
			List<Map<String, String>> resultListOfPhonesOfResidentsOfStationNumber= infoPhoneOfResidentsByStationNumberUnderTest
					.searchInfoOfResident("6");
			
			verify(personService).getAllPersons();
			verify(fireStationService).getFireStationsByStationNumber(any(String.class));
			assertTrue(resultListOfPhonesOfResidentsOfStationNumber.isEmpty());
		}catch (NullPointerException e) {
					assertThrows(NullPointerException.class,
							() -> infoPhoneOfResidentsByStationNumberUnderTest
							.searchInfoOfResident("6"));
		} catch (AssertionError e) {
			fail(e.getMessage());
		}	
	}
	
@Test
	@DisplayName("Given existing stationNumber without residents registered  when generate a map with info of no existing resident  the method should error and null ")
	void testSearchInfoOfResident_WithResidentAndPhonesNotFoundByStationNumber() throws Exception {
		when(personService.getAllPersons()).thenReturn(listOfPersonsTest);
		when(fireStationService.getFireStationsByStationNumber( "7")).thenReturn(listOfFireStationsTest2);
		
		try {
			List<Map<String, String>> resultListOfPhonesOfResidentsOfStationNumber= infoPhoneOfResidentsByStationNumberUnderTest
					.searchInfoOfResident("7");
			
			verify(personService).getAllPersons();
			verify(fireStationService).getFireStationsByStationNumber(any(String.class));
			assertTrue(resultListOfPhonesOfResidentsOfStationNumber.isEmpty());
		}catch (NullPointerException e) {
					assertThrows(NullPointerException.class,
							() -> infoPhoneOfResidentsByStationNumberUnderTest
							.searchInfoOfResident("7"));
		} catch (AssertionError e) {
			fail(e.getMessage());
		}	
	}
}
