package com.safetynet.api.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.safetynet.api.model.PersonEntity;
import com.safetynet.api.repository.IPersonRepository;

@RestController // This means that this class is a Controller
public class PersonController {


	  @Autowired // This means to get the bean called userRepository
	         // Which is auto-generated by Spring, we will use it to handle the data
	  private  IPersonRepository personRepository;

	  @PostMapping(path="/add") // Map ONLY POST Requests
	  public @ResponseBody String addNewUser (@RequestParam String name
	      , @RequestParam String email) {
	    // @ResponseBody means the returned String is the response, not a view name
	    // @RequestParam means it is a parameter from the GET or POST request

	   PersonEntity n = new PersonEntity();
	    n.setFirstName(name);
	    n.setEmail(email);
	    personRepository.save(n);
	    return "Saved";
	  }

	  @GetMapping(path="/all")
	  public @ResponseBody Iterable<PersonEntity> getAllUsers() {
	    // This returns a JSON or XML with the users
	    return     personRepository.findAll();
	  }

}
